version: '3'

services:
  product-hexagonal:
    build:
      dockerfile: ./Dockerfile
      context: .
    image: product-hexagonal
    container_name: product-hexagonal
    ports:
      - "9999:9999"

networks:
  default:
    driver: bridge
    ipam:
      config:
        - subnet: 172.16.57.0/24